-- Task 1.4: ai_response table for verifiable AI responses
-- Stores prompt, response, hash, signature, TSA token, and metadata.
-- Compatible with H2 (tests) and PostgreSQL (production).

CREATE TABLE ai_response (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    prompt          TEXT NOT NULL,
    response        TEXT NOT NULL,
    response_hash   VARCHAR(64) NOT NULL,
    signature       VARCHAR(2048),
    tsa_token       VARCHAR(4096),
    llm_model       VARCHAR(255),
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    request_id      VARCHAR(64),
    temperature     DOUBLE PRECISION,
    system_prompt   TEXT,
    version         INTEGER DEFAULT 1
);

-- Index for lookup by id (primary key) and by created_at for audit queries
CREATE INDEX idx_ai_response_created_at ON ai_response (created_at);
CREATE INDEX idx_ai_response_request_id ON ai_response (request_id);
