-- Phase 4: minimal analytics events (landing view, CTA click, demo view, evidence download).

CREATE TABLE metrics_event (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_name   VARCHAR(64) NOT NULL,
    response_id  BIGINT,
    created_at   TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_metrics_event_name ON metrics_event (event_name);
CREATE INDEX idx_metrics_event_created_at ON metrics_event (created_at);
